package com.proxima.mobile;

import android.content.ActivityNotFoundException;
import android.content.Intent;

import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;

@CapacitorPlugin(name = "ARPlugin")
public class ARPlugin extends Plugin {

    /**
     * Called from JavaScript/TypeScript via Capacitor bridge.
     * Parses a full intent:// URI (as generated by model-viewer) and starts
     * Google Scene Viewer via startActivity(), bypassing the WebView entirely.
     */
    @PluginMethod
    public void openSceneViewer(PluginCall call) {
        String intentUri = call.getString("intentUri");
        if (intentUri == null || intentUri.isEmpty()) {
            call.reject("intentUri is required");
            return;
        }
        try {
            Intent intent = Intent.parseUri(intentUri, Intent.URI_INTENT_SCHEME);
            getActivity().startActivity(intent);
            call.resolve();
        } catch (ActivityNotFoundException e) {
            call.reject("Scene Viewer not available on this device");
        } catch (Exception e) {
            call.reject("Failed to launch AR: " + e.getMessage());
        }
    }
}
